#!/usr/bin/env python3
"""
VACA Campaign 50 — Rebuild Entry Points
========================================
The per-file scaffolder's OLD buildTsEntryPoint fabricated import names from
node labels when a file had no detected exports (`import { scheme_picker }`)
and re-exported duplicate names (TS2300), breaking `tsc --noEmit` on nearly
every build. The backend is now fixed; this script regenerates the ALREADY
scaffolded index.ts files from each build's dependency-graph.json (which
records the real per-node exports) using the same corrected logic:

  - file with no usable export → side-effect import: import './src/x/y.ts';
  - duplicate export names → aliased: import { main as main_1 } ...
  - re-export block deduped

Then re-runs the static scan.

Usage:
  python3 scripts/rebuild-entrypoints.py
"""

import json, os, re, subprocess, sys

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(BASE, "data/campaign50-manifest.json")
SCAN_SCRIPT = os.path.join(BASE, "scripts", "scan-campaign-50.py")
LOG = os.path.join(BASE, "data", "campaign50-entrypoints.md")


def sanitize(name: str) -> str:
    s = (name or "").lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    s = re.sub(r"^-|-$", "", s)
    return s or "untitled"


def build_ts_entry(graph: dict, project_name: str, app_goal: str = "") -> str:
    nodes = graph.get("nodes", [])
    ts_nodes = [n for n in nodes if (n.get("language") or "").lower() in ("typescript", "javascript")]
    lines = [
        "/**",
        f" * {project_name} — Auto-generated entry point",
        " * Generated by Visual AI Code Architect",
        " * Each node is a standalone file in src/",
        " */",
        "",
    ]
    imported = set()
    for n in ts_nodes:
        safe = sanitize(n.get("nodeLabel", ""))
        fname = n.get("fileName", "index.ts")
        exports = [e for e in (n.get("exports") or []) if isinstance(e, str) and e.strip()]
        if not exports:
            lines.append(f"import './src/{safe}/{fname}';")
            continue
        first = exports[0]
        local = first
        if first in imported:
            i = 1
            while f"{first}_{i}" in imported:
                i += 1
            local = f"{first}_{i}"
        imported.add(local)
        if local == first:
            lines.append(f"import {{ {first} }} from './src/{safe}/{fname}';")
        else:
            lines.append(f"import {{ {first} as {local} }} from './src/{safe}/{fname}';")
    lines += ["", "// ── App Bootstrap ──", f"console.log('🚀 {project_name} starting...');",
              "console.log('Target: linux');"]
    if app_goal:
        lines.append(f"console.log('Goal: {app_goal}');")
    lines.append("")
    if ts_nodes and imported:
        lines.append(f"// {len(ts_nodes)} TypeScript modules loaded and ready")
        lines.append("export {")
        for local in sorted(imported):
            lines.append(f"  {local},")
        lines.append("};")
    return "\n".join(lines)


def main():
    with open(MANIFEST) as f:
        manifest = json.load(f)
    builds = manifest.get("builds", [])
    log_lines = ["# VACA Campaign 50 — Entry Point Rebuild Log", ""]
    regenerated = 0
    skipped = []
    for b in builds:
        out = b.get("outputDir", "")
        if not out or not os.path.isdir(out):
            skipped.append(b["name"])
            continue
        graph_path = os.path.join(out, "dependency-graph.json")
        if not os.path.isfile(graph_path):
            skipped.append(b["name"])
            continue
        try:
            with open(graph_path) as f:
                graph = json.load(f)
        except Exception:
            skipped.append(b["name"])
            continue
        code = build_ts_entry(graph, b["name"], b.get("goal", ""))
        with open(os.path.join(out, "index.ts"), "w") as f:
            f.write(code)
        regenerated += 1
        log_lines.append(f"- {b['name']}: regenerated index.ts ({len(graph.get('nodes', []))} nodes)")
    with open(LOG, "w") as f:
        f.write("\n".join(log_lines) + "\n")
    print(f"=== Regenerated {regenerated} entry points; skipped: {skipped or 'none'} ===")
    print(f"    Log: {LOG}")
    print("\n=== Re-scanning ===")
    r = subprocess.run([sys.executable, SCAN_SCRIPT], cwd=BASE, capture_output=True, text=True)
    print(r.stdout[-4000:])
    if r.returncode != 0:
        print("SCAN STDERR:", r.stderr[-1500:])


if __name__ == "__main__":
    main()
